quadrotor_env:
  sim_dt: 0.02
  max_t: 10.0
  control_mode: ctbr   # motor | ctbr
  world_box: [[-10, 20.0], [-10.0, 20.0], [0.0, 50.0]]  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  init_pos: [0, 0, 40.0]                   # base reset position [x,y,z]
  randomize_position_on_reset: false
  randomize_position_scale: 5.0   # scale for position noise around init_pos
  randomize_velocity_on_reset: false
  randomize_velocity_scale: 1.0   # scale for initial linear velocity noise
  randomize_attitude_on_reset: false   # false -> start level (identity quaternion)
  randomize_attitude_scale: 1.0   # attitude random scale (used only when randomize_attitude_on_reset=true)
  camera:
     # Camera pose in quadrotor body frame (B -> C)
     # pos [0.0, 0.0, -0.3] quaternion [0.7071, -0.7071, 0.0, 0.0] -> 아래 보기
     # pos [0.0, 0.0, 0.3] quaternion [1.0, 0.0, 0.0, 0.0] -> 앞에 보기
    rel_pos: [0.0, 0.0, -0.3]           # [x, y, z] meters
    rel_quat_wxyz: [0.7071, -0.7071, 0.0, 0.0]  # quaternion [w, x, y, z]
    width: 256
    height: 256
    fov: 70.0
    log_world_pose: false
    log_world_pose_interval_steps: 50
    # 3 QR tag centers in world frame
    tag_centers_world:
      - [5.5, 6.5, 3.0]
      - [-2.3, 4.1, 3.0]
      - [-0.6, 8.0, 3.0]
    # For each tag: 4 corners in world frame (p0->p1->p2->p3)
    # shape: [[[x,y,z] x4] x3]
    tag_corners_world:
      - # tag 0
        - [9.5, 2.5, 3.0]
        - [1.5, 2.5, 3.0]
        - [1.5, 10.5, 3.0]
        - [9.5, 10.5, 3.0]
      - # tag 1
        - [-0.3, 2.1, 3.0]
        - [-4.3, 2.1, 3.0]
        - [-4.3, 6.1, 3.0]
        - [-0.3, 6.1, 3.0]
      - # tag 2
        - [0.4, 7.0, 3.0]
        - [-1.6, 7.0, 3.0]
        - [-1.6, 9.0, 3.0]
        - [ 0.4, 9.0, 3.0]
    # Backward-compatible single-tag keys (optional)
    tag_center_world: [5.5, 6.5, 3.0]
    tag_corner_world:
      - [9.5, 2.5, 3.0]
      - [1.5, 2.5, 3.0]
      - [1.5, 10.5, 3.0]
      - [9.5, 10.5, 3.0]

quadrotor_dynamics:
  mass: 0.73
  arm_l: 0.17
  motor_omega_min: 150.0 # motor rpm min
  motor_omega_max: 3000.0 # motor rpm max
  motor_tau: 0.0001 # motor step response
  thrust_map: [1.3298253500372891e-06, 0.0038360810526746033, 
      -1.7689986848125325]
  kappa: 0.016 # rotor drag coeff
  omega_max: [6.0, 6.0, 6.0]  # body rate constraint (x, y, z) 

rl:
  ######terminal 조건######################################################################
  landing_terminal_z: 3.02  #consider terminted when z<terminal_Z
  landing_tilt_hard: 10 #terminate when tilt exceeds this [radian]


  ######Success 조건######################################################################
  landing_success_xy_error: 0.5  #xy error needs to be smaller than this to succeed
  landing_success_vz: 0.25  #z error needs to be smaller than this to succeed
  landing_success_tilt: 0.3 #tilt(pitch and roll) needs to be smaller than this to succeed
  landing_success_vxy: 0.3  #xy speed needs to be smaller than this to succeed
  landing_success_body_rate: 0.3 #body-rate norm needs to be smaller than this to succeed
  landing_success_reward: 100.0
  landing_failure_reward: -10.0
  landing_tilt_hard_penalty: -20.0 # penalty when exceeding landing tilt


  ########### 로그 ##############
  log_interval_steps: 1 # ___ step 마다 로그 출력

  ####### reward ###########################################################################
  landing_w_xy: 100 #xy position difference penalty weight
  landing_xy_reward_scale: 0.2 #scale factor in reward_xy = w_xy / (1 + scale * xy_error)
  landing_w_z: 0.5 #z position difference penalty weight
  landing_w_action_hover: 0.5 #penalty weight for deviation from [9.81, 0, 0, 0] action

  ###############설정값#############################################################
  hold_last_tag_obs: true # whether to hold the last observed tag pose when the tag is not observed (e.g., during landing when the tag is on the ground and not visible)
