quadrotor_env:
  sim_dt: 0.02
  max_t: 10.0
  control_mode: ctbr   # motor | ctbr
  world_box: [[-10, 20.0], [-10.0, 20.0], [0.0, 50.0]]  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  init_pos: [5.5, 6.5, 40.0]                   # base reset position [x,y,z]
  randomize_position_on_reset: true
  randomize_position_scale: 5.0   # scale for position noise around init_pos
  randomize_velocity_on_reset: false
  randomize_velocity_scale: 1.0   # scale for initial linear velocity noise
  randomize_attitude_on_reset: false   # false -> start level (identity quaternion)
  randomize_attitude_scale: 1.0   # attitude random scale (used only when randomize_attitude_on_reset=true)
  camera:
     # Camera pose in quadrotor body frame (B -> C)
     # pos [0.0, 0.0, -0.3] quaternion [0.7071, -0.7071, 0.0, 0.0] -> 아래 보기
     # pos [0.0, 0.0, 0.3] quaternion [1.0, 0.0, 0.0, 0.0] -> 앞에 보기
    rel_pos: [0.0, 0.0, -0.3]           # [x, y, z] meters
    rel_quat_wxyz: [0.7071, -0.7071, 0.0, 0.0]  # quaternion [w, x, y, z]
    width: 256
    height: 256
    fov: 70.0
    log_world_pose: false
    log_world_pose_interval_steps: 50
    dot_world_pos: [5.5, 6.5, 3.0]
    # 3 QR tag centers in world frame
    tag_centers_world:
      - [5.5, 6.5, 3.0]
      - [-2.3, 4.1, 3.0]
      - [-0.6, 8.0, 3.0]
    # For each tag: 4 corners in world frame (p0->p1->p2->p3)
    # shape: [[[x,y,z] x4] x3]
    tag_corners_world:
      - # tag 0
        - [9.5, 2.5, 3.0]
        - [1.5, 2.5, 3.0]
        - [1.5, 10.5, 3.0]
        - [9.5, 10.5, 3.0]
      - # tag 1
        - [-0.3, 2.1, 3.0]
        - [-4.3, 2.1, 3.0]
        - [-4.3, 6.1, 3.0]
        - [-0.3, 6.1, 3.0]
      - # tag 2
        - [0.4, 7.0, 3.0]
        - [-1.6, 7.0, 3.0]
        - [-1.6, 9.0, 3.0]
        - [ 0.4, 9.0, 3.0]
    # Backward-compatible single-tag keys (optional)
    tag_center_world: [5.5, 6.5, 3.0]
    tag_corner_world:
      - [9.5, 2.5, 3.0]
      - [1.5, 2.5, 3.0]
      - [1.5, 10.5, 3.0]
      - [9.5, 10.5, 3.0]

quadrotor_dynamics:
  mass: 0.73
  arm_l: 0.17
  motor_omega_min: 150.0 # motor rpm min
  motor_omega_max: 3000.0 # motor rpm max
  motor_tau: 0.0001 # motor step response
  thrust_map: [1.3298253500372891e-06, 0.0038360810526746033, 
      -1.7689986848125325]
  kappa: 0.016 # rotor drag coeff
  omega_max: [0.8, 0.8, 0.5]  # body rate constraint (x, y, z) 

rl:
  #########hovering rewards#######################################################
  pos_coeff: -0.05        # reward coefficient for position
  ori_coeff: -0.05        # reward coefficient for orientation
  lin_vel_coeff: -0.005   # reward coefficient for linear velocity
  ang_vel_coeff: -0.005   # reward coefficient for angular velocity
  act_coeff: -0.01  # reward coefficient for control actions

  